version: '3.3'

services:
  db:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_DATABASE: 'godb'
      MYSQL_USER: 'godatabase'
      MYSQL_PASSWORD: 'godatabase'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - godb:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d

volumes:
  godb:
